<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Purchase Order {{ $purchaseOrder->po_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1f2933; }
        h1 { font-size: 18px; margin-bottom: 0; }
        .subtitle { color: #52606d; margin-top: 4px; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #cbd2d9; padding: 6px 8px; text-align: left; }
        th { background-color: #f0f4f8; }
        .text-right { text-align: right; }
        .meta { width: 100%; margin-bottom: 15px; }
        .meta td { border: none; padding: 2px 0; }
        .grand-total { font-weight: bold; }
        .footer { margin-top: 30px; font-size: 10px; color: #7b8794; }
    </style>
</head>
<body>
    <h1>LARIOS PHARMACY &mdash; Purchase Order</h1>
    <p class="subtitle">PO Number: {{ $purchaseOrder->po_number }} &nbsp;|&nbsp; Date: {{ $purchaseOrder->created_at?->format('Y-m-d') }}</p>

    <table class="meta">
        <tr>
            <td><strong>Supplier:</strong> {{ $purchaseOrder->supplier->name }}</td>
            <td><strong>Email:</strong> {{ $purchaseOrder->supplier->email }}</td>
        </tr>
        <tr>
            <td><strong>Address:</strong> {{ $purchaseOrder->supplier->address }}</td>
            <td><strong>Expected Delivery:</strong> {{ $purchaseOrder->expected_delivery_date?->format('Y-m-d') }}</td>
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th class="text-right">Qty</th>
                <th class="text-right">Unit Cost</th>
                <th class="text-right">Subtotal</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($purchaseOrder->items as $item)
                <tr>
                    <td>{{ $item->product->name ?? 'Product #' . $item->product_id }}</td>
                    <td class="text-right">{{ $item->quantity_ordered }}</td>
                    <td class="text-right">{{ number_format($item->unit_cost, 2) }}</td>
                    <td class="text-right">{{ number_format($item->subtotal, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="grand-total">
                <td colspan="3" class="text-right">Grand Total</td>
                <td class="text-right">{{ number_format($purchaseOrder->total_value, 2) }}</td>
            </tr>
        </tfoot>
    </table>

    @if ($purchaseOrder->is_auto_generated)
        <p class="footer">Auto-generated by inventory system</p>
    @endif
</body>
</html>
